version: '3.1'

services:
  api:
    build: ../api
    container_name: api
    restart: always
    env_file:
      - ../api/.env
    ports:
      - "8000:8000"
    networks:
      - event-manager
      
  frontend:
    build: ../frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - event-manager

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - event-manager

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - event-manager

  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    ports:
      - "6379:6379"
    networks:
      - event-manager
    
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    networks:
      - event-manager

networks:
  event-manager:
    driver: bridge